require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'RnCrypto' do
  config = use_native_modules!

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  # Pods for RnCrypto
  pod 'IDZSwiftCommonCrypto', '~> 0.13'
  use_react_native!(
    :path => config[:reactNativePath],
    # By default, Hermes is disabled on Old Architecture, and enabled on New Architecture.
    # You can enabled/disable it manually by replacing `flags[:hermes_enabled]` with `true` or `false`.
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RnCryptoTests' do 
    inherit! :complete
  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
